/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javadatabase;

import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;


/**
 *
 * @author FANISAM
 */

public class MainFrame extends javax.swing.JFrame {
    private int idEdit = -1; // ID untuk edit, bukan row
    DefaultTableModel modelmahasiswa;
    boolean isEdit;


    /**
     * Creates new form MainFrame
     */

    public MainFrame() {
        initComponents();
        String[] kolom = {"ID", "NAMA", "NIM", "JENIS", "SKS", "BIAYA"};
        modelmahasiswa = new DefaultTableModel(kolom, 0);
        tblMhs.setModel(modelmahasiswa);
        
        cmbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[] {"Reguler", "Beasiswa", "Internasional"}
));
        
        isEdit = false;
        loadData(); // Load data saat aplikasi mulai
}
      // Method untuk load data dari DB ke tabel
    private void loadData() {
        modelmahasiswa.setRowCount(0);
        java.util.List<Object[]> list = JavaDataBase.getAll();
        for (Object[] row : list) {
            modelmahasiswa.addRow(row);
    }
}
    private void hitungBiayaOtomatis() {
    try {
        String jenis = cmbJenis.getSelectedItem().toString();
        int sks = Integer.parseInt(txtSKS.getText());
        int tahun = Integer.parseInt(txtTahunMasuk.getText().isEmpty() ? "0" : txtTahunMasuk.getText());

        mahasiswa m;
        if (jenis.equals("Reguler")) {
            m = new MahasiswaReguler(0, "", "", tahun, sks);
        } else if (jenis.equals("Beasiswa")) {
            m = new MahasiswaBeasiswa(0, "", "", tahun, sks);
        } else {
            m = new MahasiswaInternasional(0, "", "", tahun, sks);
        }

        lblBiaya.setText("Rp " + String.format("%,.0f", m.hitungBiayaKuliah()));

    } catch (NumberFormatException e) {
        lblBiaya.setText("Rp 0");
    }
}
    private void clearForm() {
    txtNama.setText("");
    txtNim.setText("");
    txtTahunMasuk.setText("");
    txtSKS.setText("");
    cmbJenis.setSelectedIndex(0);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNama = new javax.swing.JTextField();
        txtNim = new javax.swing.JTextField();
        lblNama = new javax.swing.JLabel();
        lblNim = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMhs = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        txtTahunMasuk = new javax.swing.JTextField();
        lblTahunMasuk = new javax.swing.JLabel();
        btnTampilkan = new javax.swing.JButton();
        btnUpload = new javax.swing.JButton();
        lblSKS = new javax.swing.JLabel();
        txtSKS = new javax.swing.JTextField();
        lblJenis = new javax.swing.JLabel();
        cmbJenis = new javax.swing.JComboBox<>();
        lblBiaya = new javax.swing.JLabel();
        lblBiayaa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        lblNama.setText("Masukan Nama");

        lblNim.setText("Masukan Nim");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        tblMhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMhs);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        txtTahunMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTahunMasukActionPerformed(evt);
            }
        });

        lblTahunMasuk.setText("Masukan TahunMasuk");

        btnTampilkan.setText("Tampilkan");
        btnTampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilkanActionPerformed(evt);
            }
        });

        btnUpload.setText("Upload csv");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        lblSKS.setText("Jumlah SKS");

        txtSKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSKSActionPerformed(evt);
            }
        });

        lblJenis.setText("Jenis Mahasiswa");

        cmbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJenisActionPerformed(evt);
            }
        });

        lblBiaya.setText("Rp. 0");
        lblBiaya.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblBiayaKeyReleased(evt);
            }
        });

        lblBiayaa.setText("Biaya Kuliah");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpload)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTampilkan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEdit))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNim, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTahunMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSKS, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblBiayaa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTahunMasuk)
                            .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(txtNim)
                            .addComponent(txtSKS)
                            .addComponent(cmbJenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTahunMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTahunMasuk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSKS)
                    .addComponent(txtSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJenis)
                    .addComponent(cmbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBiaya)
                    .addComponent(lblBiayaa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpload)
                    .addComponent(btnTampilkan)
                    .addComponent(btnTambah)
                    .addComponent(btnHapus)
                    .addComponent(btnEdit))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
                                      
    String nama = txtNama.getText().trim();
    String nim = txtNim.getText().trim();
    String tahunStr = txtTahunMasuk.getText().trim();
    String sksStr = txtSKS.getText().trim();
    String jenis = cmbJenis.getSelectedItem().toString();

    if (nama.isEmpty() || nim.isEmpty() || tahunStr.isEmpty() || sksStr.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
        return;
    }

    try {
        int tahun = Integer.parseInt(tahunStr);
        int sks = Integer.parseInt(sksStr);

        mahasiswa m;
        if (jenis.equals("Reguler")) {
            m = new MahasiswaReguler(0, nim, nama, tahun, sks);
        } else if (jenis.equals("Beasiswa")) {
            m = new MahasiswaBeasiswa(0, nim, nama, tahun, sks);
        } else {
            m = new MahasiswaInternasional(0, nim, nama, tahun, sks);
        }

        if (isEdit) {
            if (JavaDataBase.update(idEdit, m, jenis)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
            }
            isEdit = false;
            idEdit = -1;
        } else {
            JavaDataBase.insert(m, jenis);
            javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
        }

        loadData();
        clearForm();

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Tahun & SKS harus angka!");
    }
        
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int row = tblMhs.getSelectedRow();
        if (row != -1) {
        int id = Integer.parseInt(tblMhs.getValueAt(row, 0).toString());
        if (JavaDataBase.delete(id)) {
            loadData();
            javax.swing.JOptionPane.showMessageDialog(this, "Data dihapus!");
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih data!");
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    int row = tblMhs.getSelectedRow();
    if (row != -1) {
        idEdit = Integer.parseInt(tblMhs.getValueAt(row, 0).toString());
        txtNama.setText(tblMhs.getValueAt(row, 1).toString());
        txtNim.setText(tblMhs.getValueAt(row, 2).toString());
        cmbJenis.setSelectedItem(tblMhs.getValueAt(row, 3).toString());
        txtSKS.setText(tblMhs.getValueAt(row, 4).toString());
        isEdit = true;
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih data!");
    }            
            
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtTahunMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTahunMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTahunMasukActionPerformed

    private void btnTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilkanActionPerformed
        // TODO add your handling code here
         loadData(); // Load ulang data dari DB
    }//GEN-LAST:event_btnTampilkanActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:                                          
    JFileChooser chooser = new JFileChooser();
    int result = chooser.showOpenDialog(this);

    if (result == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            br.readLine(); // skip header CSV

            while ((line = br.readLine()) != null) {
                String[] data = line.split(",");

                String nama = data[0];
                String nim = data[1];
                int tahun = Integer.parseInt(data[2]);
                String jenis = data[3];
                int sks = Integer.parseInt(data[4]);

                mahasiswa m;
                if (jenis.equalsIgnoreCase("Reguler")) {
                    m = new MahasiswaReguler(0, nim, nama, tahun, sks);
                } else if (jenis.equalsIgnoreCase("Beasiswa")) {
                    m = new MahasiswaBeasiswa(0, nim, nama, tahun, sks);
                } else {
                    m = new MahasiswaInternasional(0, nim, nama, tahun, sks);
                }

                JavaDataBase.insert(m, jenis);
            }

            loadData();
            javax.swing.JOptionPane.showMessageDialog(this, "Upload CSV berhasil!");

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal upload CSV: " + e.getMessage());
        }
    }

    }//GEN-LAST:event_btnUploadActionPerformed

    private void txtSKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSKSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSKSActionPerformed

    private void cmbJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJenisActionPerformed
        // TODO add your handling code here:
         hitungBiayaOtomatis();
    }//GEN-LAST:event_cmbJenisActionPerformed

    private void lblBiayaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblBiayaKeyReleased
        // TODO add your handling code here:
         hitungBiayaOtomatis();
    }//GEN-LAST:event_lblBiayaKeyReleased

    /**
     * @param args  command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTampilkan;
    private javax.swing.JButton btnUpload;
    private javax.swing.JComboBox<String> cmbJenis;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBiaya;
    private javax.swing.JLabel lblBiayaa;
    private javax.swing.JLabel lblJenis;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNim;
    private javax.swing.JLabel lblSKS;
    private javax.swing.JLabel lblTahunMasuk;
    private javax.swing.JTable tblMhs;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtSKS;
    private javax.swing.JTextField txtTahunMasuk;
    // End of variables declaration//GEN-END:variables
}



