/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javadatabase;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FANISAM
 */

public class MainFrame extends javax.swing.JFrame {
    private int idEdit = -1; // ID untuk edit, bukan row
    DefaultTableModel modelmahasiswa;
    boolean isEdit;


    /**
     * Creates new form MainFrame
     */

  public MainFrame() {
        initComponents();
        String[] kolom = {"ID", "NAMA", "NIM", "TahunMasuk"};
        modelmahasiswa = new DefaultTableModel(kolom, 0);
        tblMhs.setModel(modelmahasiswa);
        isEdit = false;
        loadData(); // Load data saat aplikasi mulai
}
      // Method untuk load data dari DB ke tabel
    private void loadData() {
        modelmahasiswa.setRowCount(0); // Clear tabel
        java.util.List<mahasiswa> list = JavaDataBase.getAll();
        for (mahasiswa m : list) {
            Object[] row = {m.getId(), m.getNama(), m.getNim(), m.getTahunMasuk()};
            modelmahasiswa.addRow(row);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNama = new javax.swing.JTextField();
        txtNim = new javax.swing.JTextField();
        lblNama = new javax.swing.JLabel();
        lblNim = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMhs = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        txtTahunMasuk = new javax.swing.JTextField();
        lblTahunMasuk = new javax.swing.JLabel();
        btnTampilkan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        lblNama.setText("Masukan Nama");

        lblNim.setText("Masukan Nim");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        tblMhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMhs);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        txtTahunMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTahunMasukActionPerformed(evt);
            }
        });

        lblTahunMasuk.setText("Masukan TahunMasuk");

        btnTampilkan.setText("Tampilkan");
        btnTampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilkanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTampilkan)
                        .addGap(18, 18, 18)
                        .addComponent(btnTambah)
                        .addGap(17, 17, 17)
                        .addComponent(btnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNim, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTahunMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTahunMasuk)
                            .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(txtNim))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTahunMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTahunMasuk))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnTampilkan)
                    .addComponent(btnTambah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
                                      
      String nama = txtNama.getText().trim();
      String nim = txtNim.getText().trim();
      String tahunStr = txtTahunMasuk.getText().trim();
 
     // Validasi input
        if (nama.isEmpty() || nim.isEmpty() || tahunStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
            return;
        }
        
        try {
            int tahun = Integer.parseInt(tahunStr);
            mahasiswa m = new mahasiswa(nim, nama, tahun);
            
            if (isEdit) {
                // Mode edit → update DB dengan ID yang disimpan
                m.setId(idEdit);
                if (JavaDataBase.update(m)) {
                    loadData(); // Refresh tabel
                    javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Gagal memperbarui data!");
                }
                isEdit = false;
                idEdit = -1;
                 } else {
                // Mode tambah → insert ke DB dan ambil ID baru
                int newId = JavaDataBase.insert(m);
                if (newId != -1) {
                    m.setId(newId);
                    Object[] dataBaru = {m.getId(), nama, nim, tahun};
                    modelmahasiswa.addRow(dataBaru);
                    javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Gagal menambahkan data!");
                }
                }
                
                 // Kosongkan textfield
            txtNama.setText("");
            txtNim.setText("");
            txtTahunMasuk.setText("");
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Tahun Masuk harus berupa angka!");
        }
        
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
                    // TODO add your handling code here:
             int row = tblMhs.getSelectedRow();
        if (row != -1) {
            int id = Integer.parseInt(tblMhs.getValueAt(row, 0).toString());
            if (JavaDataBase.delete(id)) {
                modelmahasiswa.removeRow(row);
                javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus data!");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus!");
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
       int row = tblMhs.getSelectedRow();
        if (row != -1) {
            // Kolom: 0=ID, 1=NAMA, 2=NIM, 3=TahunMasuk
            int id = Integer.parseInt(tblMhs.getValueAt(row, 0).toString());
            String nama = (String) tblMhs.getValueAt(row, 1);
            String nim = (String) tblMhs.getValueAt(row, 2);
            int tahunMasuk = Integer.parseInt(tblMhs.getValueAt(row, 3).toString());
            txtNama.setText(nama);
            txtNim.setText(nim);
            txtTahunMasuk.setText(String.valueOf(tahunMasuk));
            this.isEdit = true;
            this.idEdit = id; // Simpan ID untuk update
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diedit!");
        }
            
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtTahunMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTahunMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTahunMasukActionPerformed

    private void btnTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilkanActionPerformed
        // TODO add your handling code here
         loadData(); // Load ulang data dari DB
    }//GEN-LAST:event_btnTampilkanActionPerformed

    /**
     * @param args  command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTampilkan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNim;
    private javax.swing.JLabel lblTahunMasuk;
    private javax.swing.JTable tblMhs;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtTahunMasuk;
    // End of variables declaration//GEN-END:variables
}



